// outbound-webhook.ino — automatica example: a temperature + humidity sensor
// that fires an outbound HTTPS webhook whenever its readings change, using
// Particle.publish() wired to a Particle webhook integration.
//
// DEVICE ARCHETYPE: temperature + humidity sensor node (Photon 2 / Argon / Boron
// with a DHT22 or SHT31) that reports readings to Alexa AND simultaneously POSTs
// to an external HTTPS endpoint (e.g. a Home Assistant REST endpoint, an IFTTT
// webhook, or a custom API). The on-device outbound path is a single
// Particle.publish(); all HTTPS transport lives in the Particle webhook
// integration configured in the Particle Console (or via the Particle API) —
// no extra library needed on the device.
//
// ALEXA CAPABILITIES EXPOSED:
//   'e' Alexa.TemperatureSensor (read-only, SINGLETON; tempDeci + scale)
//   'n' Alexa.RangeController "Humidity" (read-only, SINGLETON; 0..100 int)
//
// ALEXA UTTERANCES ENABLED:
//   "Alexa, what is the temperature of the basement sensor?"
//   "Alexa, what is the humidity of the basement sensor?"
//
// OUTBOUND WEBHOOK FLOW:
//   1. The sketch calls Particle.publish("sensor/state", jsonPayload, PRIVATE).
//   2. A Particle webhook integration (configured once in the Console / API) matches
//      the event name "sensor/state", injects any extra headers or body template,
//      and POSTs the JSON payload to WEBHOOK_URL.
//   3. The integration can add a static Authorization header (Bearer token, API key,
//      or Basic auth) in its "headers" config — no secret ever touches the firmware.
//   4. Particle retries the POST automatically (up to 3 times with back-off) if the
//      target server returns a non-2xx response.
//
// PARTICLE WEBHOOK INTEGRATION CONFIG (paste into the Particle Console or API):
//   {
//     "name":        "sensor-outbound",
//     "event":       "sensor/state",
//     "url":         "https://api.example.com/sensor",
//     "requestType": "POST",
//     "headers": {
//       "Content-Type":  "application/json",
//       "X-Device-Id":   "{{PARTICLE_DEVICE_ID}}",
//       "Authorization": "Bearer <your-token-here>"
//     },
//     "body":        "{{{PARTICLE_EVENT_VALUE}}}",
//     "noDefaults":  true,
//     "rejectUnauthorized": true
//   }
//   — PARTICLE_DEVICE_ID and PARTICLE_EVENT_VALUE are Particle-reserved template vars.
//   — Set "noDefaults": true to suppress the extra Particle system fields in the body.
//   — The Authorization header stays in the integration config (never in firmware).
//
// GOTCHAS:
//   1. Particle.publish() is rate-limited to 1 event/second per device. The automatica
//      library already coalesces state publishes to <=1/sec (kPublishMinIntervalMs);
//      the extra "sensor/state" publish below adds a second event per sensor-read
//      cycle. Space reads at least 2 s apart, or combine the automatica reportState()
//      publish with the outbound publish by using a shared event name — see note below.
//   2. Particle.publish() with PRIVATE sends only to YOUR Particle account; it is
//      never routed to other users. The webhook integration subscribes server-side.
//   3. The sketch builds a small JSON payload manually to avoid pulling in ArduinoJson
//      or std::to_string (both work fine on Device-OS but add overhead). Replace with
//      your preferred JSON builder.
//   4. Particle.publish() returns a bool (true on success). On failure (no cloud
//      connection) the event is dropped — the webhook will not fire. Gate the call on
//      Particle.connected() if delivery guarantees matter for your use case.
//   5. .ino preprocessor rule: the onControl callback prototype is auto-generated by
//      the .ino toolchain ABOVE the first #include, so the parameter type must be
//      FULLY QUALIFIED (automatica::CtlCommand) for the generated prototype to compile.
//      See the 'using namespace automatica' note below.
//
// COMBINING automatica state publish with the outbound event (advanced):
//   AutomaticaCloud::publish() uses the event name "automatica/<thing>/state".
//   You can configure your Particle webhook integration to match that event name
//   instead of a dedicated "sensor/state" event — then every automatica reportState()
//   call also triggers the webhook without an extra Particle.publish() call. The
//   payload shape is Ascii85-encoded binary (SPEC §1.8), so your webhook target
//   must decode it. For human-readable JSON at the target, keep a dedicated publish
//   as shown here.

// NOTE: no library-namespace types in free-function signatures above the first
// #include (the .ino preprocessor emits prototypes here). onControl uses the fully-
// qualified automatica::CtlCommand — DO NOT change it to CtlCommand.
#include "automatica.h"
#include "AutomaticaCloud.h"

using namespace automatica;

// ---------------------------------------------------------------------------
// Core automatica + Particle cloud adapter
// ---------------------------------------------------------------------------
Automatica home;              // the facade: holds endpoints, manifest, callback.
                              // NB: do NOT name this 'automatica' (namespace clash).
AutomaticaCloud cloud(home);  // Particle Device-OS adapter; ctor calls home.setCloudPort(this).

// ---------------------------------------------------------------------------
// Sensor state (replace with real DHT22 / SHT31 reads in your sketch)
// ---------------------------------------------------------------------------
static int gTempDeci    = 220;  // temperature in tenths of a degree C (22.0 °C)
static int gHumidityPct = 55;   // relative humidity 0..100 %

// Endpoint index — captured from addEndpoint(); used in updateSensorReadings()
// and the initial setInitialState() calls.
static int gSensorEp = -1;

// ---------------------------------------------------------------------------
// Control callback — sensors are read-only; no Alexa directives are expected.
// The parameter type is fully qualified (automatica::CtlCommand) because the
// .ino toolchain emits the prototype ABOVE the first #include / 'using namespace'.
// ---------------------------------------------------------------------------
static bool onControl(const automatica::CtlCommand& cmd, void*) {
    (void)cmd;
    return false;  // read-only sensor: every directive becomes an Alexa error
}

// ---------------------------------------------------------------------------
// buildPayload — build the JSON body sent to the outbound webhook.
//   {"temperature":22.0,"humidity":55}
// Written without snprintf to keep this example dependency-free. In production
// you can use snprintf(), String::format(), or ArduinoJson.
// ---------------------------------------------------------------------------
static String buildPayload(int tempDeci, int humidityPct) {
    int intPart  = tempDeci / 10;
    int fracPart = tempDeci % 10;
    if (fracPart < 0) fracPart = -fracPart;  // handle negative temperatures
    // Compose with Particle's String (available on all Device-OS targets).
    String s = "{\"temperature\":";
    s += String(intPart);
    s += '.';
    s += String(fracPart);
    s += ",\"humidity\":";
    s += String(humidityPct);
    s += '}';
    return s;
}

// ---------------------------------------------------------------------------
// updateSensorReadings — push new readings into automatica (-> Alexa) and
// fire the outbound webhook publish (-> Particle webhook integration -> HTTPS).
// ---------------------------------------------------------------------------
static void updateSensorReadings(int tempDeci, int humidityPct) {
    if (gSensorEp < 0) return;

    // -- Update automatica state (this will be reported to Alexa via reportState) --
    { CapState s; s.tempDeci = tempDeci; s.scale = "CELSIUS";
      home.setInitialState(gSensorEp, kCapTemperatureSensor, kNoInstance, s); }
    { CapState s; s.i = humidityPct;
      home.setInitialState(gSensorEp, kCapHumidity, kNoInstance, s); }
    home.reportState(gSensorEp);  // coalesced, <=1 publish/sec, event "automatica/<thing>/state"

    // -- Fire the outbound webhook event (-> Particle webhook integration) --
    // Gate on cloud connectivity so we do not silently fail while offline.
    if (Particle.connected()) {
        String payload = buildPayload(tempDeci, humidityPct);
        // "sensor/state" must match the "event" field in the webhook integration config.
        Particle.publish("sensor/state", payload, PRIVATE);
    }
}

// ---------------------------------------------------------------------------
// setup()
// ---------------------------------------------------------------------------
void setup() {
    Serial.begin(115200);

    // Register the sensor endpoint.
    //   id   "basement-sensor"    — stable internal id (^[a-z0-9_-]{1,24}$, must not
    //                               change across reboots — it is part of the device identity).
    //   name "Basement Sensor"    — Alexa friendlyName.
    //   cat  TEMPERATURE_SENSOR   — Alexa displayCategory.
    gSensorEp = home.addEndpoint("basement-sensor", "Basement Sensor",
                                  "Temperature and humidity sensor",
                                  {"TEMPERATURE_SENSOR"});

    // Add capabilities (both singletons — addressed by code + kNoInstance).
    home.addTemperatureSensor(gSensorEp);  // 'e' Alexa.TemperatureSensor (read-only)
    home.addHumiditySensor(gSensorEp);     // 'n' Alexa.RangeController "Humidity" (read-only)

    // Seed the initial state (must be called before begin()).
    { CapState s; s.tempDeci = gTempDeci; s.scale = "CELSIUS";
      home.setInitialState(gSensorEp, kCapTemperatureSensor, kNoInstance, s); }
    { CapState s; s.i = gHumidityPct;
      home.setInitialState(gSensorEp, kCapHumidity, kNoInstance, s); }

    home.onControl(onControl);  // register the (reject-all) callback; required even for read-only endpoints
    home.begin();               // build the manifest + register Particle var/function. Call once.
}

// ---------------------------------------------------------------------------
// loop()
// ---------------------------------------------------------------------------
static unsigned long lastReadMs = 0;

void loop() {
    home.loop();  // REQUIRED every loop: flush debounced state publishes + emit initial snapshot

    // Read sensors every 60 s.  Spacing reads >=2 s apart avoids running into the
    // Particle 1-event/sec rate limit (automatica emits one state publish; we add one
    // outbound publish — two events per cycle at most, well within the budget at 60 s).
    unsigned long now = millis();
    if (now - lastReadMs >= 60000UL) {
        lastReadMs = now;
        // In production replace the stubs with real sensor reads:
        //   gTempDeci    = (int)(dht.readTemperature() * 10.0f);
        //   gHumidityPct = (int)dht.readHumidity();
        updateSensorReadings(gTempDeci, gHumidityPct);
    }
}
