// deep-sleep-sensor.ino — automatica example
// ============================================================================
// DEVICE ARCHETYPE: a BATTERY-POWERED climate sensor (temperature + humidity) that wakes
//   on a timer, reports its readings AND its battery level via a Particle.publish vitals
//   event, then deep-sleeps to conserve the LiPo. Because SLEEP_MODE_DEEP powers the
//   MCU down and resets RAM, EACH wake re-runs setup() from the top — so the entire
//   "connect → read → reportState → sleep" cycle lives in setup(); loop() is effectively
//   unreachable and is only present to satisfy the Arduino sketch contract.
//
//   One endpoint ("porch"), two read-only sensor capabilities, plus battery vitals.
//
// CAPABILITIES (endpoint "porch", display category TEMPERATURE_SENSOR):
//   'e' addTemperatureSensor — Alexa.TemperatureSensor (SINGLETON, read-only).
//                              CapState.tempDeci (tenths of degC) + CapState.scale.
//   'n' addHumiditySensor    — Alexa.RangeController "Humidity" (SINGLETON, read-only).
//                              CapState.i (whole-percent RH 0..100).
//   Battery level is NOT an Alexa capability here — it rides a separate
//   Particle.publish event ("automatica/vitals") so the cloud health view
//   shows battery charge state alongside the Alexa state snapshot.
//
// ALEXA UTTERANCES THIS ENABLES (query only — nothing to command):
//   "Alexa, what's the temperature on the porch?"
//   "Alexa, what's the humidity on the porch?"
//
// POWER MODEL (Particle Device-OS):
//   System.sleep(SLEEP_MODE_DEEP, kSleepSeconds) puts the Photon/Argon/Boron into
//   deep sleep for kSleepSeconds seconds, then the hardware resets — setup() runs
//   again from the top. System.resetReason() distinguishes the very first power-on
//   (RESET_REASON_POWER_DOWN / RESET_REASON_PIN_RESET) from a scheduled deep-sleep
//   wake (RESET_REASON_SLEEP_TIMER / RESET_REASON_UNKNOWN on Gen 2) for logging.
//   Battery voltage is read from an analog pin through a resistor divider; call
//   analogRead() once before sleeping (the ADC is unavailable during sleep).
//
// HARDWARE WIRING ASSUMPTIONS:
//   * readTempDeci() / readHumidityPct() are stubs — replace with your DHT22 /
//     SHT31 / BME280 driver (tenths-of-degC and whole-percent RH respectively).
//   * Battery voltage: the LiPo pack feeds kBatteryPin through a 2:1 voltage
//     divider (two equal resistors). On a Photon/Argon/Boron the ADC reference is
//     3.3 V and resolution is 12 bits (0..4095). Adjust kBatteryPin and the divider
//     ratio for your board; set kBatteryPin to A5 or similar as needed.
//   * Gen 2 (Photon): use SLEEP_MODE_DEEP. Deep-sleep wake on Gen 2 resets the
//     device, so setup() runs from the top on every wake — the same as the ESP32
//     deep-sleep pattern in esp32/automatica/examples/deep-sleep-sensor.
//   * Gen 3 (Argon/Boron): SLEEP_MODE_DEEP is supported identically via the same
//     System.sleep() call; the device re-runs setup() on timer wake.
//
// GOTCHAS:
//   * CONSTRUCTION / LOOP ORDER: construct Automatica + AutomaticaCloud at GLOBAL
//     scope so they survive the full wake before System.sleep() is called. In
//     setup(): build the endpoint + caps, call begin(), seed + reportState(), flush
//     with a short home.loop() pump, publish battery vitals, THEN call
//     System.sleep(SLEEP_MODE_DEEP, kSleepSeconds) LAST. Nothing after sleep() runs.
//   * System.sleep() DOES NOT RETURN — never put cleanup after it. loop() below only
//     exists to satisfy the Arduino contract and as a safety re-sleep if execution
//     somehow reaches it (e.g. during a Device-OS OTA update that suppresses sleep).
//   * Sensors are REPORTED, not controlled: onControl rejects everything (returns
//     false) but MUST still be registered because onControl() requires a non-null
//     function pointer.
//   * Both 'e' and 'n' are SINGLETON caps — seed/address with instance == kNoInstance.
//   * .ino preprocessor prototype rule: onControl fully-qualifies
//     automatica::CtlCommand because Arduino hoists its auto-prototype above
//     `using namespace automatica;`.
//   * Particle.publish is rate-limited to 1 event/sec per device. The automatica
//     state publish and the battery vitals publish are issued sequentially; a 1100 ms
//     delay is inserted between them so neither is dropped.
//   * SLEEP_MODE_DEEP on Gen 2 (Photon) does NOT support pin-wakeup alongside a
//     timer; on Gen 3 (Argon/Boron) use SystemSleepConfiguration for combined
//     wakeup sources if needed. This example uses timer-only.
//
// SPEC §14 (Power Management / Deep-Sleep + Battery) + §9 (vitals fields).
// ============================================================================

// NOTE: onControl forward-prototype is auto-generated by the Arduino preprocessor
// ABOVE this include block, so the parameter type must be fully qualified as
// automatica::CtlCommand (see Gotchas above). Do NOT put any automatica types in
// free-function signatures that appear before the first #include.

#include "automatica.h"
#include "AutomaticaCloud.h"

using namespace automatica;

// ---- Core automatica + Particle cloud transport --------------------------------
Automatica home;                 // facade; never name it 'automatica' (namespace clash)
AutomaticaCloud cloud(home);     // ctor calls home.setCloudPort(this) — wires Particle.variable/.function/.publish

// ---- Sleep + battery configuration --------------------------------------------
// kSleepSeconds — wake/report cadence. 300 s = 5 min. Adjust for your battery budget.
static const int kSleepSeconds = 300;

// kBatteryPin — analog pin wired to the LiPo through a 2:1 voltage divider.
// Photon: A0..A5 are valid ADC pins (12-bit, 0..4095, Vref = 3.3 V).
// Change to whichever pin your board uses; set to A5 for typical LiPo shields.
static const pin_t kBatteryPin = A5;

// kAdcMaxCount — 12-bit ADC full scale on Particle devices (2^12 - 1).
static const float kAdcMaxCount = 4095.0f;

// kAdcVref — ADC reference voltage in millivolts (3.3 V on Photon/Argon/Boron).
static const float kAdcVref_mV = 3300.0f;

// kDividerRatio — voltage divider ratio applied before the ADC pin (default 2:1,
// i.e. two equal resistors). The raw ADC voltage is half the actual pack voltage.
static const float kDividerRatio = 2.0f;

// Endpoint index (set in setup, one "porch" climate sensor).
static int gEp;

// ---- Hardware stubs: replace with your DHT22 / SHT31 / BME280 driver ----------
// readTempDeci(): temperature in TENTHS of a degree Celsius (215 == 21.5 degC).
static int readTempDeci()    { return 0; }
// readHumidityPct(): relative humidity as a whole percent (0..100).
static int readHumidityPct() { return 0; }

// ---- Battery sense ------------------------------------------------------------
// batteryMilliVolts(): read the LiPo pack voltage in mV via the ADC divider.
// Returns 0 if kBatteryPin < 0 (USB-powered / no battery sense).
static uint16_t batteryMilliVolts() {
    int raw = analogRead(kBatteryPin);                          // 0..4095
    float voltage_mV = (raw / kAdcMaxCount) * kAdcVref_mV * kDividerRatio;
    return (uint16_t)voltage_mV;
}

// batteryPercent(): approximate state-of-charge (0..100) from pack voltage.
// Uses a simple two-point linear map for a LiPo: 3000 mV = 0 %, 4200 mV = 100 %.
// Replace with a proper SoC table or fuel-gauge IC reading if available.
static uint8_t batteryPercent() {
    uint16_t mv = batteryMilliVolts();
    if (mv <= 3000) return 0;
    if (mv >= 4200) return 100;
    return (uint8_t)(((uint32_t)(mv - 3000) * 100) / 1200);
}

// ---- Control callback ---------------------------------------------------------
// Read-only sensors accept no directives — reject everything. Must still be
// registered (onControl requires a non-null function pointer). SPEC §1.6.
static bool onControl(const automatica::CtlCommand& cmd, void*) {
    (void)cmd;
    return false;   // read-only sensor -> Lambda returns an Alexa error for any directive
}

// ---- Battery vitals publish ---------------------------------------------------
// Publish a compact JSON vitals event that folds in battery level (SPEC §9.2 +
// §14.5 fields "mv"/"pct") and the wake/reset reason. Event name follows the
// convention "automatica/vitals" so the cloud can route it independently of Alexa
// state. PRIVATE ensures the event is scoped to the device's owner.
static void publishBatteryVitals() {
    uint16_t mv  = batteryMilliVolts();   // raw pack voltage, mV (0 = no sensor). §14.5
    uint8_t  pct = batteryPercent();      // state-of-charge estimate 0..100.       §14.5
    int      reason = (int)System.resetReason();
    // reason: RESET_REASON_SLEEP_TIMER (10) on a normal deep-sleep timer wake;
    //         RESET_REASON_POWER_DOWN (0) or RESET_REASON_PIN_RESET (3) on first power-on.
    char payload[96];
    snprintf(payload, sizeof(payload),
             "{\"mv\":%u,\"pct\":%u,\"resetReason\":%d}",
             (unsigned)mv, (unsigned)pct, reason);
    // Vitals are a live stream, not a retained snapshot — publish PRIVATE, not retained.
    Particle.publish("automatica/vitals", String(payload), PRIVATE);
}

// ---- setup() — the ENTIRE wake cycle -----------------------------------------
// Deep-sleep reboots here each interval. SPEC §14.6.
// ---------------------------------------------------------------------------
void setup() {
    Serial.begin(115200);

    // Log the reset reason so a serial monitor shows whether this is a first
    // power-on or a scheduled timer wake. RESET_REASON_SLEEP_TIMER (10) = timer wake.
    Serial.printlnf("[power] resetReason=%d (10=sleep-timer, 0/3=power-on/pin)",
                    (int)System.resetReason());

    // ---- Endpoint + read-only capabilities ------------------------------------
    gEp = home.addEndpoint("porch", "Porch Climate", "automatica battery climate sensor",
                           {"TEMPERATURE_SENSOR"});
    home.addTemperatureSensor(gEp);   // 'e' singleton read-only temperature
    home.addHumiditySensor(gEp);      // 'n' singleton read-only humidity %

    home.onControl(onControl);        // required even though it only rejects

    // ---- Seed the initial reported state from the current sensor readings -----
    { CapState t; t.tempDeci = readTempDeci(); t.scale = "CELSIUS";
      home.setInitialState(gEp, kCapTemperatureSensor, kNoInstance, t); }
    { CapState h; h.i = readHumidityPct();
      home.setInitialState(gEp, kCapHumidity, kNoInstance, h); }

    // ---- Build the manifest + register Particle.variable/function ------------
    // Particle.connected() returns true when the cloud session is already up
    // (Photon reconnects automatically). begin() may be called before the cloud
    // is fully joined; the first loop() call flushes the snapshot publish once
    // connected. SPEC §1.8.
    home.begin();

    // ---- Mark the endpoint dirty so reportState will publish its state --------
    // reportState() queues a coalesced publish; home.loop() below flushes it.
    home.reportState(gEp);

    // ---- FLUSH: pump home.loop() briefly so the QoS state publish actually
    //      goes out over Particle.publish before the radio powers down.
    //      Without this the state publish can be dropped when we sleep immediately.
    //      The facade rate-limits to <=1 publish/sec; 30 iterations × 100 ms = 3 s
    //      budget is ample for a single state publish on an already-connected device.
    for (int i = 0; i < 30; ++i) {
        home.loop();
        delay(100);
    }

    // ---- Publish battery vitals AFTER the state publish to avoid rate-limit
    //      collisions (Particle allows 1 event/sec per device). The 1100 ms gap
    //      ensures neither publish is silently dropped. SPEC §9.2 / §14.5.
    delay(1100);
    publishBatteryVitals();

    // ---- Arm the deep-sleep timer and sleep. DOES NOT RETURN. ----------------
    // The MCU powers down here and reboots into setup() after kSleepSeconds.
    // On Gen 2 (Photon): SLEEP_MODE_DEEP uses the RTC for the timer.
    // On Gen 3 (Argon/Boron): same API; Device-OS handles the HAL difference.
    Serial.printlnf("[power] sleeping %d s", kSleepSeconds);
    Serial.flush();
    System.sleep(SLEEP_MODE_DEEP, kSleepSeconds);   // DOES NOT RETURN
}

// ---- loop() — unreachable in normal operation --------------------------------
// setup() sleeps before returning. Present to satisfy the Arduino contract; if
// execution somehow reaches here (e.g. OTA update suppressed the sleep), re-sleep
// defensively so the battery device never busy-loops awake. SPEC §14.6.
void loop() {
    System.sleep(SLEEP_MODE_DEEP, kSleepSeconds);   // safety re-sleep (does not return)
}
