// device-vitals.ino — automatica example: device health telemetry via
// Particle.variable (cloud-readable) + Particle.publish (webhook-forwardable).
//
// DEVICE ARCHETYPE: a light-switch node (Photon / Argon / Boron) that:
//   1. Controls one Alexa-addressable light (on/off).
//   2. Exposes four live health diagnostics as Particle cloud variables so the
//      Console and any webhook/integration can read them at any time:
//        vitals_heap     — free SRAM in bytes (System.freeMemory())
//        vitals_uptime   — seconds since last boot (System.uptime())
//        vitals_rssi     — WiFi RSSI in dBm (WiFi.RSSI(); -999 if not applicable)
//        vitals_fw       — Device-OS semantic version string (System.version())
//   3. Publishes a periodic "device/vitals" event (PRIVATE, every 60 s and on
//      boot) carrying the same four fields as a compact JSON blob so a Particle
//      webhook can forward them to a logger/dashboard without polling the device.
//   4. Exposes the last reset reason as a Particle cloud variable (vitals_reset)
//      so crash-loops can be diagnosed from the cloud.
//
// ALEXA CAPABILITIES EXPOSED:
//   'o' Alexa.PowerController — TurnOn/TurnOff (bool)
//
// ALEXA UTTERANCES ENABLED:
//   "Alexa, turn on the workshop light."
//   "Alexa, turn off the workshop light."
//
// VITALS EVENT (Particle webhook topic):
//   Name:    "device/vitals"
//   Payload: {"fw":"<ver>","up":<s>,"heap":<bytes>,"rssi":<dBm>,"reset":"<reason>"}
//   Published on boot and every kVitalsIntervalMs (60 000 ms by default).
//   Wire a Particle webhook to forward this event to your logger endpoint.
//   See examples/logger-ingest for the webhook pattern.
//
// PARTICLE CLOUD VARIABLES (readable from Console / API at any time):
//   vitals_heap   (int)    — System.freeMemory() in bytes
//   vitals_uptime (int)    — System.uptime() in seconds (wraps at ~136 years)
//   vitals_rssi   (int)    — WiFi.RSSI() in dBm; -999 on cellular-only platforms
//   vitals_fw     (String) — System.version() e.g. "5.6.0"
//   vitals_reset  (String) — human-readable last reset reason
//
// GOTCHAS:
//   1. .ino PROTOTYPE RULE: onControl uses the fully-qualified automatica::CtlCommand
//      type in its parameter list because the Arduino preprocessor auto-generates the
//      forward prototype and inserts it ABOVE the `using namespace automatica;` line.
//   2. Particle.variable() for int mirrors a global int — the core library updates it
//      in-place; Particle does NOT hold a copy. Keep gVitalsHeap etc. as file-scope
//      globals (not stack locals) so the binding stays valid.
//   3. WiFi.RSSI() returns 0 / is undefined on cellular (Boron/Electron). We guard
//      with #ifdef PLATFORM_ID checks and fall back to -999 so the variable is always
//      a valid int.
//   4. System.uptime() returns uint32_t (seconds). It wraps in ~136 years; safe to
//      store in an int for normal device lifetimes.
//   5. Particle cloud variables are limited to 20 per device; this sketch uses 5.
//      Particle.variable() with a String requires a String (not std::string) or a
//      char[]. We use a global String for vitals_fw and vitals_reset.
//   6. Particle.publish() is rate-limited to ~1 event/sec per device. The 60 s
//      vitals interval is well inside that budget. Guard with Particle.connected()
//      before publishing so boot-time calls do not queue-stall.
//   7. SYSTEM_THREAD(ENABLED) is recommended so cloud processing and application
//      loop() run concurrently. Without it, a slow sensor read in loop() stalls
//      the cloud keepalive.

// NB: onControl prototype is auto-generated by the .ino preprocessor ABOVE this
// include, so the parameter type must be fully qualified (automatica::CtlCommand).
// Do NOT move the function definition above this include.
#include "automatica.h"
#include "AutomaticaCloud.h"

// SYSTEM_THREAD: lets the cloud thread handle Particle.publish / keepalive
// independently of the application loop(). Safe on all Gen2/Gen3 platforms.
SYSTEM_THREAD(ENABLED);

using namespace automatica;

// ---- automatica facade -------------------------------------------------------
Automatica home;                 // Never name it 'automatica' (namespace clash).
AutomaticaCloud cloud(home);     // ctor: home.setCloudPort(&cloud).

// ---- endpoint index (set in setup(), used in loop() and onControl()) --------
static int gLightEp = -1;

// ---- device state ------------------------------------------------------------
static bool gOn = false;

// ---- vitals mirror variables (Particle.variable binds to these addresses) ---
// Must be file-scope so the binding outlives setup(). Particle.variable(int)
// reads the value at &gVitalsHeap on every Console/API query — keep it fresh.
static int    gVitalsHeap   = 0;   // bytes free (System.freeMemory())
static int    gVitalsUptime = 0;   // seconds since boot (System.uptime())
static int    gVitalsRssi   = 0;   // dBm (WiFi.RSSI()) or -999 on cellular
static String gVitalsFw;           // Device-OS version string (System.version())
static String gVitalsReset;        // human-readable reset reason

// ---- vitals publish interval -------------------------------------------------
static const unsigned long kVitalsIntervalMs = 60000UL;  // 60 s
static unsigned long gLastVitalsMs = 0;

// ---------------------------------------------------------------------------
// resetReasonString() — maps System.resetReason() enum to a short label.
// Keeps the vitals payload human-readable without requiring a JSON library.
// SPEC §9.2 parallel: "reset" field in the vitals JSON.
// ---------------------------------------------------------------------------
static String resetReasonString() {
    switch (System.resetReason()) {
        case RESET_REASON_PIN_RESET:        return "pin";
        case RESET_REASON_POWER_MANAGEMENT: return "power-mgmt";
        case RESET_REASON_POWER_DOWN:       return "power-down";
        case RESET_REASON_POWER_BROWNOUT:   return "brownout";
        case RESET_REASON_WATCHDOG:         return "watchdog";
        case RESET_REASON_UPDATE:           return "ota-update";
        case RESET_REASON_UPDATE_TIMEOUT:   return "ota-timeout";
        case RESET_REASON_FACTORY_RESET:    return "factory-reset";
        case RESET_REASON_SAFE_MODE:        return "safe-mode";
        case RESET_REASON_DFU_MODE:         return "dfu-mode";
        case RESET_REASON_PANIC:            return "panic";
        case RESET_REASON_USER:             return "user";
        case RESET_REASON_UNKNOWN:
        default:                            return "unknown";
    }
}

// ---------------------------------------------------------------------------
// refreshVitals() — reads current Device-OS diagnostics into the mirror
// globals so that:
//   a) Particle cloud variable queries see fresh data immediately, and
//   b) publishVitals() can build the JSON from already-updated fields.
// Call from both setup() (first reading) and the 60 s loop tick.
// ---------------------------------------------------------------------------
static void refreshVitals() {
    gVitalsHeap   = static_cast<int>(System.freeMemory());
    gVitalsUptime = static_cast<int>(System.uptime());

    // WiFi.RSSI() is valid on Wi-Fi platforms (Photon, Argon, P2).
    // On cellular (Boron, Electron) it returns 0 or is undefined; use -999
    // as a sentinel so the cloud consumer can distinguish "no Wi-Fi" from
    // "RSSI = 0 dBm" (which would indicate a saturated signal, rarely real).
#if Wiring_WiFi
    gVitalsRssi = static_cast<int>(WiFi.RSSI());
#else
    gVitalsRssi = -999;   // cellular platform — RSSI not applicable
#endif

    // System.version() returns a const char* to the Device-OS semver string,
    // e.g. "5.6.0". Copy once per refresh; the pointer is stable but the String
    // copy is cheap and safe for the Particle.variable binding.
    gVitalsFw = String(System.version());
}

// ---------------------------------------------------------------------------
// publishVitals() — fires a PRIVATE "device/vitals" event carrying a JSON
// payload with all four health metrics + the reset reason.
// Wire a Particle webhook (name: "device/vitals") to forward this to your
// logger. See examples/logger-ingest for the webhook configuration pattern.
// Guard with Particle.connected() — never queue-publish while disconnected
// (the event queue is limited and a disconnected publish silently drops).
// ---------------------------------------------------------------------------
static void publishVitals() {
    if (!Particle.connected()) return;

    // Build a compact JSON string without a heap-heavy library. All fields are
    // simple scalars; no escaping needed for the version string (semver contains
    // only digits and dots) or the reset reason (enum-mapped to safe literals above).
    String payload = String::format(
        "{\"fw\":\"%s\",\"up\":%d,\"heap\":%d,\"rssi\":%d,\"reset\":\"%s\"}",
        gVitalsFw.c_str(),
        gVitalsUptime,
        gVitalsHeap,
        gVitalsRssi,
        gVitalsReset.c_str()
    );

    Particle.publish("device/vitals", payload, PRIVATE);
}

// ---------------------------------------------------------------------------
// Hardware stub: drive the relay / LED that controls the light.
// Replace with your real GPIO. D7 is the Photon/Argon on-board LED —
// handy for a wiring-free demo.
// ---------------------------------------------------------------------------
static void applyPower(bool on) {
    digitalWrite(D7, on ? HIGH : LOW);
}

// ---------------------------------------------------------------------------
// Control callback — invoked by the library after it decodes a validated
// automaticaCtl command from the cloud (Ascii85 -> binary -> CtlCommand).
//   cmd.code    : capability code ('o' = PowerController here).
//   cmd.boolVal : for PowerController, the requested state (true = ON).
// Return true == handled (Lambda reports success to Alexa).
// Return false == unhandled (Lambda returns an Alexa error).
//
// NOTE: the .ino preprocessor inserts the forward prototype for this function
// ABOVE the `using namespace automatica;` line, so the parameter type MUST be
// the fully-qualified automatica::CtlCommand — not just CtlCommand.
// ---------------------------------------------------------------------------
static bool onControl(const automatica::CtlCommand& cmd, void*) {
    if (cmd.code == kCapPower) {
        gOn = cmd.boolVal;
        applyPower(gOn);
        return true;
    }
    return false;   // unknown directive -> Alexa error
}

// ---------------------------------------------------------------------------
// setup()
// ---------------------------------------------------------------------------
void setup() {
    Serial.begin(115200);
    pinMode(D7, OUTPUT);

    // ---- Collect reset reason FIRST (before anything reinitialises state) ----
    // System.resetReason() is only valid until the next reset; read it now and
    // store it in a file-scope String that refreshVitals() and publishVitals() use.
    gVitalsReset = resetReasonString();

    // ---- Seed vitals mirror variables (before Particle.variable registration) --
    // Particle.variable() binds to the address of the global — the value must be
    // valid from the moment registration returns.
    refreshVitals();

    // ---- Register Particle cloud variables (max 20 per device; we use 5) ------
    // These are READ-ONLY from the cloud side; the device writes them via
    // refreshVitals(). Names are limited to 64 chars; values up to 1024 bytes.
    Particle.variable("vitals_heap",   gVitalsHeap);
    Particle.variable("vitals_uptime", gVitalsUptime);
    Particle.variable("vitals_rssi",   gVitalsRssi);
    Particle.variable("vitals_fw",     gVitalsFw);
    Particle.variable("vitals_reset",  gVitalsReset);

    // ---- automatica: declare the endpoint + capability -----------------------
    gLightEp = home.addEndpoint("workshop-light", "Workshop Light",
                                 "automatica device-vitals example", {"LIGHT"});
    home.addPower(gLightEp);

    // Initial state: light OFF. setInitialState seeds the first cloud snapshot.
    { CapState s; s.b = false; home.setInitialState(gLightEp, kCapPower, kNoInstance, s); }

    home.onControl(onControl);
    home.begin();   // build manifest + register Particle var/function. Call once, after all add*().

    // ---- Publish the boot-time vitals event (non-blocking; queued by Device-OS) --
    // If not yet connected this is a no-op (publishVitals() guards with connected()).
    // The 60 s timer will retry on the next tick once connected.
    publishVitals();
    gLastVitalsMs = millis();
}

// ---------------------------------------------------------------------------
// loop()
// ---------------------------------------------------------------------------
void loop() {
    home.loop();   // REQUIRED every loop: flushes debounced state publishes + emits initial snapshot.

    // ---- Periodic vitals refresh + publish (every kVitalsIntervalMs = 60 s) --
    unsigned long now = millis();
    if (now - gLastVitalsMs >= kVitalsIntervalMs) {
        gLastVitalsMs = now;
        // Refresh the mirror globals first so Particle.variable queries see fresh
        // values, THEN publish the event (publishVitals() reads from the globals).
        refreshVitals();
        publishVitals();

        // Log to Serial for local debugging (remove in production to save code space).
        Serial.printlnf("[vitals] heap=%d up=%ds rssi=%ddBm fw=%s reset=%s",
                        gVitalsHeap, gVitalsUptime, gVitalsRssi,
                        gVitalsFw.c_str(), gVitalsReset.c_str());
    }
}
